### ISSUE TITLE
To few documentation

### ISSUE THREAD

**Issue by matthiasbeyer** [softprops/hubcaps#106]
I'm trying to build  [a simple tool](https://github.com/matthiasbeyer/git-dit-github-import/) for exporting github issues to another tool, though my code does not return from `Issues::list() -> wait()`. The documentation is not clear (there is none) why this does not work as intended.

[Here](https://github.com/mario-kr/git-dit-github-import/blob/minify-example/src/main.rs) is a minified example (thanks @mario-kr).

**Comment by softprops** [comment]
Hi @matthiasbeyer. Sorry for the delay.

The issue here looks to be a notable gotcha in [futures](http://alexcrichton.com/futures-rs/futures/future/trait.Future.html#method.wait) where calling this blocks the current thread. I noticed this by cloning the repo.

I think it's more appropriate here to use a `Core` to run the future. This small diff should do the trick. 

```diff
-    let core       = Core::new().expect("Cannot initialize tokei Core");
+    let mut core       = Core::new().expect("Cannot initialize tokei Core");
     let github     = Github::new(useragent, None, &core.handle());
     let issues     = Issues::new(github, username, reponame);

     progress.set_message("Fetching issue list");
-    let issue_list = issues.list(&IssueListOptions::default())
-        .wait()
+    let issue_list = core.run(issues.list(&IssueListOptions::default()))
         .expect("Failed to fetch issues!");

     for issue in issue_list.iter() {
         progress.set_message(&format!("Fetching issue {}", issue.number));
         let iref : IssueRef<_> = Issues::get(&issues, issue.number);
-        iref.comments()
-            .list(&CommentListOptions::default())
-            .wait()
+        core.run(iref.comments()
+            .list(&CommentListOptions::default()))
             .expect(&format!("Failed to get comments for issue {}", issue.number))
```

I tested this and it works ( I like the little spinner! )

```bash
cargo run -- matthiasbeyer kairos
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/git-dit-github-import matthiasbeyer kairos`
⠉ Fetching issue list
Got comment 334451992 for issue 1 from matthiasbeyer
  Done
```

As an aside I just published a new version of hubcaps which should fix some pagination issues you may run into. Let me know if you find anything else!
