### ISSUE TITLE
Error listing my repositories - `Err(Decoding(ExpectedError("String", "null")))`

### ISSUE THREAD

**Issue by carols10cents** [softprops/hubcaps#24]
Hi! I see in #21 that you mention deserialization has been a bunch of trial and error... and I think I have an error for you to try :)

When I try and list my repositories, I get `Err(Decoding(ExpectedError("String", "null")))`. This is the code i'm using, also available [in a convenient github repository](https://github.com/carols10cents/hubcaps_test)!

```
extern crate hyper;
extern crate hubcaps;

use hubcaps::Github;

fn main() {
    let client = hyper::Client::new();
    let github = Github::new(
        "my-cool-user-agent/0.1.0",
        &client,
        None::<String>,
    );
    println!("{:?}", github.user_repos("carols10cents").list());
}
```

If there's any other information I can provide, please let me know! I might take a look at the json and see if I can figure this out, and if so i'll send in a PR, but I wanted to file the issue either way :)

**Comment by softprops** [comment]
Hi. This looks to be a case where a field in repository payload looked like it would be provided but it's actually null able and should be represented with an optional string instead of a plain string. I added debug level logging to help debug these situations. If you can install the env log crate, init it in your main func and run RUST_LOG=debug cargo run you should see the raw json payload in your console. If you can paste that here that would be great.

I actually have a branch that ports the serialization bits to serde so a pr would cause a comflict if you branch from master now. I hope to have that published soon with some other changes so if I can figure out what field is nullable, I can get that in the next release as well. Thanks for reporting the issue!

**Comment by carols10cents** [comment]
The raw json in the console wasn't as pretty as just looking at https://api.github.com/users/carols10cents/repos in the browser, so looking in that for "null" shows that the following fields on repo can be null:

* mirror_url
* homepage
* language
* description

It looks like mirror_url, homepage, and language are already `Option<String>`, but [description is not](https://github.com/softprops/hubcaps/blob/master/src/rep.rs#L477), so that must be it!

**Comment by softprops** [comment]
Thanks. I may be simpler to add a desc to your repost for now and I'll be sure to make that field and option in the next release

**Comment by softprops** [comment]
I wasn't able to reproduce a fetch returning a null for  `description` fields so I think I'm going to skip making this change in the next release. I'll keep the issue open in the meantime incase it pops up else where as a historical reminder.

**Comment by carols10cents** [comment]
Yeah, I fixed my repos so that it would stop happening for me.. it seemed to be older repos; newer ones without a description had empty string instead of null. I suspect this will be easier to reproduce once paging is supported :)
